name: Docker (test runner)

on:
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-test-runner.yml'

env:
  ORG: opendatacube
  IMAGE: datacube-tests
  BUILDER_TAG: _build_cache
  DOCKER_USER: gadockersvc


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Test Runner Docker
      run: |
        docker pull ${ORG}/${IMAGE}:latest         || true
        docker pull ${ORG}/${IMAGE}:${BUILDER_TAG} || true

        # build and cache first stage (env_builder)
        docker build \
          --target env_builder \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --tag        ${ORG}/${IMAGE}:${BUILDER_TAG} \
          ./docker/

        # now build second stage making sure first stage is from cache
        docker build \
          --cache-from ${ORG}/${IMAGE}:${BUILDER_TAG} \
          --cache-from ${ORG}/${IMAGE}:latest \
          --tag        ${ORG}/${IMAGE}:latest \
          ./docker/

    - name: DockerHub Push
      if: |
        github.ref == 'refs/heads/master' ||
        github.ref == 'refs/heads/kk-gh-actions'
      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker push ${ORG}/${IMAGE}:${BUILDER_TAG}
        docker push ${ORG}/${IMAGE}:latest
