name: Run Datacube Test Suite and Packaging

on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/run-tests.yml'
      - '!docker/**'
      - '!examples/**'
      - '!docs/**'
      - '!contrib/**'

env:
  DKR: opendatacube/datacube-tests:latest

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull Docker
      run: |
        docker pull ${DKR}

    - name: Check Code Style
      run: |
        docker run --rm  \
          -v $(pwd):/src/datacube-core \
          -e SKIP_DB=yes \
          ${DKR} \
          pycodestyle tests integration_tests examples utils --max-line-length 120

    - name: Lint Code
      run: |
        docker run --rm  \
          -v $(pwd):/src/datacube-core \
          -e SKIP_DB=yes \
          ${DKR} \
          pylint -j 2 --reports no datacube datacube_apps

    - name: Run Tests
      run: |
        docker run --rm  \
          -v $(pwd):/src/datacube-core \
          ${DKR} \
          pytest -r a \
            --cov datacube \
            --cov-report=xml \
            --doctest-ignore-import-errors \
            --durations=5 \
            datacube \
            tests \
            datacube_apps \
            integration_tests

    - name: Build Packages
      run: |
        docker run --rm  \
          -v $(pwd):/src/datacube-core \
          -e SKIP_DB=yes \
          ${DKR} \
          python setup.py bdist_wheel sdist
        ls -lh ./dist/

    - name: Publish to dea packages repo
      if: |
        github.ref == 'refs/heads/master'
        && github.event_name == 'push'

      run: |
        echo TODO
